FROM apache/airflow:2.7.1

USER root

# Installer les dépendances système si nécessaire
RUN apt-get update && apt-get install -y --no-install-recommends \
    gcc \
    && rm -rf /var/lib/apt/lists/*

USER airflow

# Installer les dépendances Python
RUN pip install --no-cache-dir --user \
    pandas>=2.0.0 \
    psycopg2-binary>=2.9.0

COPY requirements.txt /opt/airflow/requirements.txt
RUN pip install --no-cache-dir --user -r /opt/airflow/requirements.txt